DECLARE
    A NUMBERMBERMBER;
    B NUMBERMBERMBER;
D   PROCEDURE SQURNUMR
U       X MRNUMBER
    
    BEGIN   X M(NUMBER
        X  XX
    END         X  X)XS
BEGINND         X:=X*X;
    AEGIENTERNUM
    B   AAGIENTERNUM
    SQURNUM AA=:ENTER_NUM;
    DBMSSOUTPUT=PUTLINEBA
END END END;

-----------------------------------------